name: Push build

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      host: debian-bookworm
      images: initramfs-firmware-mega-image
        initramfs-firmware-ifc6410-image initramfs-firmware-ifc6560-image
        initramfs-firmware-ecs-liva-qc710-image
        initramfs-firmware-lenovo-miix-630-image
        initramfs-firmware-lenovo-yoga-c630-image
        initramfs-firmware-sc8180x-image
        initramfs-firmware-x1e80100-crd-image

      machines: qcom-armv8a qcom-armv7a
      variants: >-
        qcom-armv8a-glibc-yocto
        qcom-armv8a-musl-yocto
        qcom-armv7a-glibc-yocto
      ref: ${{github.sha}}
      ref_type: sha
      branch: ${{github.ref_name}}
      url: ${{github.server_url}}/${{github.repository}}
    secrets: inherit
